import pickle
import joblib
import numpy as np
from .config import (
    WORD2VEC_EMBEDDINGS, FASTTEXT_WORD_EMBEDDINGS,
    FASTTEXT_NGRAM_EMBEDDINGS, WORD_TO_IDX, IDX_TO_WORD,
    NGRAM_TO_IDX, TFIDF_VECTORIZER, MIN_NGRAM, MAX_NGRAM
)

def load_pickle(path):
    with open(path, "rb") as f:
        return pickle.load(f)

def generate_ngrams(word, min_n=MIN_NGRAM, max_n=MAX_NGRAM):
    word = "<" + word + ">"
    return [
        word[i:i+n]
        for n in range(min_n, max_n + 1)
        for i in range(len(word) - n + 1)
    ]

class ArtifactStore:
    def __init__(self):
        self.loaded = False
        self.error = None
        self.word2vec_embeddings = None
        self.fasttext_word_embeddings = None
        self.fasttext_ngram_embeddings = None
        self.word_to_idx = None
        self.idx_to_word = None
        self.ngram_to_idx = None
        self.tfidf_vectorizer = None
        self._load()

    def _load(self):
        required = [
            WORD2VEC_EMBEDDINGS, FASTTEXT_WORD_EMBEDDINGS,
            FASTTEXT_NGRAM_EMBEDDINGS, WORD_TO_IDX, IDX_TO_WORD,
            NGRAM_TO_IDX, TFIDF_VECTORIZER
        ]
        missing = [str(p) for p in required if not p.exists()]
        if missing:
            self.error = (
                "Missing model artifacts. Copy the files generated by "
                "Colab into models/. Missing: " + ", ".join(missing)
            )
            return
        try:
            self.word2vec_embeddings = np.load(WORD2VEC_EMBEDDINGS)
            self.fasttext_word_embeddings = np.load(FASTTEXT_WORD_EMBEDDINGS)
            self.fasttext_ngram_embeddings = np.load(FASTTEXT_NGRAM_EMBEDDINGS)
            self.word_to_idx = load_pickle(WORD_TO_IDX)
            self.idx_to_word = load_pickle(IDX_TO_WORD)
            self.ngram_to_idx = load_pickle(NGRAM_TO_IDX)
            self.tfidf_vectorizer = joblib.load(TFIDF_VECTORIZER)
            self.loaded = True
        except Exception as exc:
            self.error = f"Could not load artifacts: {exc}"

    @property
    def embedding_dim(self):
        return None if self.word2vec_embeddings is None else self.word2vec_embeddings.shape[1]

    def get_word2vec_vector(self, word):
        if word not in self.word_to_idx:
            return None
        return self.word2vec_embeddings[self.word_to_idx[word]]

    def get_fasttext_vector(self, word):
        vectors = []
        if word in self.word_to_idx:
            vectors.append(self.fasttext_word_embeddings[self.word_to_idx[word]])
        for ngram in generate_ngrams(word):
            if ngram in self.ngram_to_idx:
                vectors.append(
                    self.fasttext_ngram_embeddings[self.ngram_to_idx[ngram]]
                )
        if not vectors:
            return np.zeros(self.embedding_dim, dtype=np.float32)
        return np.mean(vectors, axis=0)
